projectName: verloop # required
default:
  annotations:
    all:
      app.amgo.io/env: dev
  labels:
    all:
      service-name: adservice
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    tag: v0.10.2
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 300Mi
  replicaCount: 1

deployments:
  - fullnameOverride: adservice
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    service:
      type: ClusterIP
      ports:
        - port: 9555
          name: api
    containers:
      - fullnameOverride: adservice
        port: 9555
        healthcheck:
          enabled: true
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            grpc:
              port: 9555
        env:
          PORT: 9555
            
