apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: aswindevs07@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: application-tls
  namespace: dev
spec:
  secretName: application-tls
  dnsNames:
    - "poc.aswindevs.com"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer