{{- if .Values.default.privateDockerRepo }}
{{- if .Values.default.privateDockerRepo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.name" $ }}
  namespace: {{ $.Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.default.privateDockerRepo.auth}}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}