projectName: verloop # required
default:
  annotations:
    all:
      app.amgo.io/env: dev
  labels:
    all:
      service-name: shippingservice
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    tag: v0.10.2
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  replicaCount: 1

deployments:
  - fullnameOverride: shippingservice
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
    service:
      type: ClusterIP
      ports:
        - port: 50051
          name: api
    containers:
      - fullnameOverride: shippingservice
        port: 50051
        healthcheck:
          enabled: true
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 50051
          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 50051
        env:
          PORT: 50051
          DISABLE_PROFILER: "1"
            
