projectName: verloop # required
default:
  annotations:
    all:
      app.amgo.io/env: dev
  labels:
    all:
      service-name: emailservice
  image:
    repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    tag: v0.10.2
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  replicaCount: 1

deployments:
  - fullnameOverride: emailservice
    service:
      type: ClusterIP
      ports:
        - port: 5000
          name: api
    containers:
      - fullnameOverride: emailservice
        port: 5000
        healthcheck:
          enabled: true
          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 5000
          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 5000
        env:
          PORT: 5000
          DISABLE_PROFILER: "1"
            
